---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: llm-service
spec:
  releaseName: llm-service
  interval: 10m
  chart:
    spec:
      chart: llm-service
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: llm-service
        namespace: gitops-service
  values:
    imagePullSecrets:
      - name: gcr-docker-registry
    image:
      repository: ghcr.io/malike/k8s-gitops-llm-service/llm-service
      tag: latest
    configMap: environment-configmap
    nodeSelector:
      node.kubernetes.io/role: platform
      kubernetes.io/os: linux
