name: Build Init phase

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & push image
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITOPS_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITOPS_TOKEN }}"

  llm-frontend:
    needs: build
    uses: ./.github/workflows/llm-frontend.yml
    secrets: inherit

  llm-service:
    needs: build
    uses: ./.github/workflows/llm-service.yml
    secrets: inherit
