name: Build Init phase

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & push image
    runs-on: ubuntu-latest


  llm-frontend:
    needs: build
    uses: ./.github/workflows/llm-frontend.yml
    secrets: inherit

  llm-service:
    needs: build
    uses: ./.github/workflows/llm-service.yml
    secrets: inherit
