name: Build Init phase

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & push image
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITOPS_TOKEN }}


  llm-frontend:
    needs: build
    uses: ./.github/workflows/llm-frontend.yml
    secrets: inherit

  llm-service:
    needs: build
    uses: ./.github/workflows/llm-service.yml
    secrets: inherit
