name: LLM Service

on: workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITOPS_TOKEN }}


      - name: Build LLM Service
        run: make build-llm

      - name: Build and push llm service to GitHub Container Registry
        run: make docker-build-llm-push

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/malike/k8s-gitops-llm-service/llm-service
          format: 'sarif'
          severity: 'CRITICAL,HIGH' #Modify to note when to block or unblock, intentionally making pipeline loose
          output: 'trivy-results.sarif' 

      - name: Uploads Trivy Scan Reports For LLM Service
        uses: actions/upload-artifact@v2
        with:
          path: |
            trivy-results-llm.sarif          
